### ISSUE TITLE
404

### ISSUE THREAD

**Issue by libaibaba** [midopooler/CharacterAnimationUsingMediapipe#1]
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: com.google.devtools.build.lib.packages.RepositoryFetchException: no such package '@rules_cc//cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] to C:/_bzl/qvku7enk/external/rules_cc/temp6651393885901580998/master.zip: GET returned 404 Not Found

**Comment by libaibaba** [comment]
I have understood the general implementation method. Thank you for your script.

**Comment by midopooler** [comment]
> I have understood the general implementation method. Thank you for your script.

Thank you for trying out! All the best for your project!
